In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (1.1.4)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.6/dist-packages (from pandas) (1.18.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [ ]:
import pandas as pd

In [ ]:
lista_altura =[1.70, 1.65,1.83]
lista_sexo = ['f','f','m']
lista_peso = [70, 65, 83]

df = pd.DataFrame(lista_altura, columns=['Altura'])
df = pd.DataFrame({'Altura': lista_altura, 'Sexo': lista_sexo, 'Peso': lista_peso})
df

   Altura Sexo  Peso
0    1.70    f    70
1    1.65    f    65
2    1.83    m    83

In [ ]:
#resumo dos dados
df.describe()

         Altura       Peso
count  3.000000   3.000000
mean   1.726667  72.666667
std    0.092916   9.291573
min    1.650000  65.000000
25%    1.675000  67.500000
50%    1.700000  70.000000
75%    1.765000  76.500000
max    1.830000  83.000000

In [ ]:
#como adicionar todos os registros qualitativos e quantitativos
df.describe(include = 'all')

          Altura Sexo       Peso
count   3.000000    3   3.000000
unique       NaN    2        NaN
top          NaN    f        NaN
freq         NaN    2        NaN
mean    1.726667  NaN  72.666667
std     0.092916  NaN   9.291573
min     1.650000  NaN  65.000000
25%     1.675000  NaN  67.500000
50%     1.700000  NaN  70.000000
75%     1.765000  NaN  76.500000
max     1.830000  NaN  83.000000

In [ ]:
#Calculo da média da altura
edia = df['Altura'].mean()
media

1.7266666666666666

In [ ]:
#Calcula a media da altura 
mediana =df.Altura.median()
mediana

1.7

In [ ]:
moda = df.Altura.mode()
moda

0    1.65
1    1.70
2    1.83
dtype: float64

In [57]:
percentis = df.Altura.quantile([0.1, 0.25, 0.5, 0.7, 0.75])
percentis.values(10)

TypeError: ignored

In [ ]:
c = '/content/drive/MyDrive/Colab Notebooks/Aula_2/DNAC2017.csv'

sinasc = pd.read_csv(c, dtype=str)
sinasc.head(5)

  contador ORIGEM CODESTAB CODMUNNASC  ... CODPAISRES TPROBSON PARIDADE KOTELCHUCK
0        1      1  2515768     110010  ...        NaN       05        1          2
1        2      1  2516047     110018  ...        NaN       05        1          3
2        3      1  5618347     110020  ...        NaN       03        1          2
3        4      1  5618347     110020  ...        NaN       02        0          5
4        5      1  5618347     110020  ...        NaN       03        1          2

[5 rows x 61 columns]

In [ ]:
#Traansformar dados quantiativos
print(f'Tipo antes: {sinasc.PESO.dtypes}')
sinasc['PESO'] = pd.to_numeric(sinasc.PESO)
print(f'Tipo agora: {sinasc.PESO.dtypes}')

Tipo antes: object
Tipo agora: float64

In [ ]:
sinasc.IDADEMAE = pd.to_numeric(sinasc.IDADEMAE).astype(pd.Int64Dtype())
sinasc.IDADEMAE.dtypes

Int64Dtype()

In [ ]:
sinasc.IDADEPAI = pd.to_numeric(sinasc.IDADEPAI).astype(pd.Int64Dtype())
sinasc.QTDFILVIVO = pd.to_numeric(sinasc.QTDFILVIVO).astype(pd.Int64Dtype())
sinasc.APGAR1 = pd.to_numeric(sinasc.APGAR1).astype(pd.Int64Dtype())
sinasc.APGAR5 = pd.to_numeric(sinasc.APGAR5).astype(pd.Int64Dtype())
sinasc.SEMAGESTAC = pd.to_numeric(sinasc.SEMAGESTAC).astype(pd.Int64Dtype())
sinasc.CONSPRENAT = pd.to_numeric(sinasc.CONSPRENAT).astype(pd.Int64Dtype())
sinasc.SERIESCMAE = pd.to_numeric(sinasc.SERIESCMAE).astype(pd.Int64Dtype())
sinasc.QTDPARTCES = pd.to_numeric(sinasc.QTDPARTCES).astype(pd.Int64Dtype())
sinasc.QTDPARTNOR = pd.to_numeric(sinasc.QTDPARTNOR).astype(pd.Int64Dtype())
sinasc.QTDGESTANT = pd.to_numeric(sinasc.QTDGESTANT).astype(pd.Int64Dtype())
sinasc.IDADE = pd.to_numeric(sinasc.IDADEMAE).astype(pd.Int64Dtype())

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  # This is added back by InteractiveShellApp.init_path()